### PR TITLE
Update to glutin 0.21.0. Closes #157

### LINKED ISSUE #157: Update to glutin v0.21.0
Glutin v0.21.0 migration guide: https://gentz.rocks/posts/glutin-v0-21-0-migration-guide/

### PR DESCRIPTION
**Pull request by iceiix**
Closes https://github.com/iceiix/stevenarella/issues/157

Glutin v0.21.0 migration guide: https://gentz.rocks/posts/glutin-v0-21-0-migration-guide/

### CODE REVIEW

**Comment by iceiix** [comment]
Compiles and runs, but breaks compiling wasm build due to changing from https://github.com/iceiix/glutin/pull/1. Also https://github.com/iceiix/winit/pull/2

**Comment by iceiix** [comment]
Updating https://github.com/iceiix/glutin/pull/1 and https://github.com/iceiix/winit/pull/2, then `cargo build --target wasm32-unknown-unknown` doesn't error out but `cargo build` does, on glutin:

```rust
error[E0432]: unresolved import `winit::platform::macos`
 --> glutin/src/platform/macos.rs:6:26
  |
6 | pub use winit::platform::macos::*;
  |                          ^^^^^ could not find `macos` in `platform`

error[E0432]: unresolved import `winit::platform::desktop`
  --> glutin/src/platform/mod.rs:24:30
   |
24 |     pub use winit::platform::desktop::*;
   |                              ^^^^^^^ could not find `desktop` in `platform`

error[E0432]: unresolved import `winit::event_loop`
 --> glutin/src/context.rs:4:12
  |
4 | use winit::event_loop::EventLoop;
  |            ^^^^^^^^^^ could not find `event_loop` in `winit`

error[E0432]: unresolved import `winit::event_loop`
  --> glutin/src/platform_impl/macos/mod.rs:24:12
   |
24 | use winit::event_loop::EventLoop;
   |            ^^^^^^^^^^ could not find `event_loop` in `winit`

error[E0432]: unresolved import `winit::event_loop`
 --> glutin/src/windowed.rs:4:12
  |
4 | use winit::event_loop::EventLoop;
  |            ^^^^^^^^^^ could not find `event_loop` in `winit`

error[E0433]: failed to resolve: use of undeclared type or module `window`
   --> glutin/src/lib.rs:332:12
    |
332 |     Window(window::CreationError),
    |            ^^^^^^ use of undeclared type or module `window`

error[E0433]: failed to resolve: use of undeclared type or module `window`
   --> glutin/src/lib.rs:416:11
    |
416 | impl From<window::CreationError> for CreationError {
    |           ^^^^^^ use of undeclared type or module `window`

error[E0433]: failed to resolve: use of undeclared type or module `window`
   --> glutin/src/lib.rs:417:18
    |
417 |     fn from(err: window::CreationError) -> Self {
    |                  ^^^^^^ use of undeclared type or module `window`

error[E0603]: module `platform` is private
 --> glutin/src/platform/macos.rs:6:16
  |
6 | pub use winit::platform::macos::*;
  |                ^^^^^^^^

error[E0603]: module `platform` is private
  --> glutin/src/platform/mod.rs:24:20
   |
24 |     pub use winit::platform::desktop::*;
   |                    ^^^^^^^^

error[E0603]: module `window` is private
  --> glutin/src/platform_impl/macos/mod.rs:25:12
   |
25 | use winit::window::{Window, WindowBuilder};
   |            ^^^^^^

error[E0603]: module `window` is private
 --> glutin/src/windowed.rs:5:12
  |
5 | use winit::window::{Window, WindowBuilder};
  |            ^^^^^^

error: unused import: `crate::platform::macos::WindowExtMacOS`
  --> glutin/src/platform_impl/macos/mod.rs:21:5
   |
21 | use crate::platform::macos::WindowExtMacOS;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: lint level defined here
  --> glutin/src/lib.rs:81:5
   |
81 |     warnings,
   |     ^^^^^^^^
   = note: #[deny(unused_imports)] implied by #[deny(warnings)]

error: unused imports: `WindowBuilder`, `Window`
 --> glutin/src/windowed.rs:5:21
  |
5 | use winit::window::{Window, WindowBuilder};
  |                     ^^^^^^  ^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> glutin/src/context.rs:182:9
    |
179 |       ) -> Result<Context<NotCurrent>, CreationError> {
    |            ------------------------------------------ expected `std::result::Result<context::Context<context::NotCurrent>, winit::CreationError>` because of return type
...
182 | /         platform_impl::Context::new_headless(el, &pf_reqs, &gl_attr, size).map(
183 | |             |context| Context {
184 | |                 context,
185 | |                 phantom: PhantomData,
186 | |             },
187 | |         )
    | |_________^ expected enum `winit::CreationError`, found enum `CreationError`
    |
    = note: expected type `std::result::Result<context::Context<context::NotCurrent>, winit::CreationError>`
               found type `std::result::Result<context::Context<_>, CreationError>`

error: aborting due to 15 previous errors

Some errors occurred: E0308, E0432, E0433, E0603.

```

**Comment by iceiix** [comment]
Trying to fix those errors by rebasing wasm_stub on eventloop-2.0 in: https://github.com/iceiix/winit/pull/3

**Comment by iceiix** [comment]
Could merge this because it works on the native platforms, but would like to not regress at least building the wasm build. Maybe replace with different stubs.

**Comment by iceiix** [comment]
```
steven $ wasm-pack build
  
  [1/9] 🦀  Checking `rustc` version...
  [2/9] 🔧  Checking crate configuration...
  [3/9] 🎯  Adding WASM target...
  info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
  [4/9] 🌀  Compiling to WASM...
  warning: file found to be present in multiple build targets: steven/src/main.rs
     Compiling stevenarella v0.0.1 (steven)
  error[E0432]: unresolved import `glutin::VirtualKeyCode`
    --> src/ui/mod.rs:21:5
     |
  21 | use glutin::VirtualKeyCode;
     |     ^^^^^^^^^^^^^^^^^^^^^^ no `VirtualKeyCode` in the root
  
  error[E0432]: unresolved import `glutin::VirtualKeyCode`
   --> src/settings.rs:3:5
    |
  3 | use glutin::VirtualKeyCode;
    |     ^^^^^^^^^^^^^^^^^^^^^^ no `VirtualKeyCode` in the root
  
  error[E0433]: failed to resolve: could not find `EventsLoop` in `glutin`
     --> src/main.rs:222:35
      |
  222 |     let mut events_loop = glutin::EventsLoop::new();
      |                                   ^^^^^^^^^^ could not find `EventsLoop` in `glutin`
  
  error[E0433]: failed to resolve: could not find `WindowBuilder` in `glutin`
     --> src/main.rs:223:34
      |
  223 |     let window_builder = glutin::WindowBuilder::new()
      |                                  ^^^^^^^^^^^^^ could not find `WindowBuilder` in `glutin`
  
  error[E0433]: failed to resolve: could not find `dpi` in `glutin`
     --> src/main.rs:225:34
      |
  225 |         .with_dimensions(glutin::dpi::LogicalSize::new(854.0, 480.0));
      |                                  ^^^ could not find `dpi` in `glutin`
  
  error[E0433]: failed to resolve: could not find `ContextBuilder` in `glutin`
     --> src/main.rs:226:26
      |
  226 |     let window = glutin::ContextBuilder::new()
      |                          ^^^^^^^^^^^^^^ could not find `ContextBuilder` in `glutin`
  
  error[E0433]: failed to resolve: could not find `GlRequest` in `glutin`
     --> src/main.rs:229:26
      |
  229 |         .with_gl(glutin::GlRequest::GlThenGles{opengl_version: (3, 2), opengles_version: (2, 0)})
      |                          ^^^^^^^^^ could not find `GlRequest` in `glutin`
  
  error[E0433]: failed to resolve: could not find `GlProfile` in `glutin`
     --> src/main.rs:230:34
      |
  230 |         .with_gl_profile(glutin::GlProfile::Core)
      |                                  ^^^^^^^^^ could not find `GlProfile` in `glutin`
  
  error[E0433]: failed to resolve: use of undeclared type or module `Event`
     --> src/main.rs:363:9
      |
  363 |         Event::DeviceEvent{event, ..} => match event {
      |         ^^^^^ use of undeclared type or module `Event`
  
  error[E0433]: failed to resolve: use of undeclared type or module `DeviceEvent`
     --> src/main.rs:364:13
      |
  364 |             DeviceEvent::MouseMotion{delta:(xrel, yrel)} => {
      |             ^^^^^^^^^^^ use of undeclared type or module `DeviceEvent`
  
  error[E0433]: failed to resolve: use of undeclared type or module `Event`
     --> src/main.rs:406:9
      |
  406 |         Event::WindowEvent{event, ..} => match event {
      |         ^^^^^ use of undeclared type or module `Event`
  
  error[E0433]: failed to resolve: use of undeclared type or module `WindowEvent`
     --> src/main.rs:407:13
      |
  407 |             WindowEvent::CloseRequested => game.should_close = true,
      |             ^^^^^^^^^^^ use of undeclared type or module `WindowEvent`
  
  error[E0433]: failed to resolve: use of undeclared type or module `WindowEvent`
     --> src/main.rs:408:13
      |
  408 |             WindowEvent::Resized(logical_size) => {
      |             ^^^^^^^^^^^ use of undeclared type or module `WindowEvent`
  
  error[E0433]: failed to resolve: use of undeclared type or module `WindowEvent`
     --> src/main.rs:413:13
      |
  413 |             WindowEvent::ReceivedCharacter(codepoint) => {
      |             ^^^^^^^^^^^ use of undeclared type or module `WindowEvent`
  
  error[E0433]: failed to resolve: use of undeclared type or module `WindowEvent`
     --> src/main.rs:419:13
      |
  419 |             WindowEvent::MouseInput{device_id: _, state, button, modifiers: _} => {
      |             ^^^^^^^^^^^ use of undeclared type or module `WindowEvent`
  
  error[E0433]: failed to resolve: use of undeclared type or module `ElementState`
     --> src/main.rs:421:22
      |
  421 |                     (ElementState::Released, MouseButton::Left) => {
      |                      ^^^^^^^^^^^^ use of undeclared type or module `ElementState`
  
  error[E0433]: failed to resolve: use of undeclared type or module `MouseButton`
     --> src/main.rs:421:46
      |
  421 |                     (ElementState::Released, MouseButton::Left) => {
      |                                              ^^^^^^^^^^^ use of undeclared type or module `MouseBu
  
  error[E0433]: failed to resolve: use of undeclared type or module `ElementState`
     --> src/main.rs:436:22
      |
  436 |                     (ElementState::Pressed, MouseButton::Right) => {
      |                      ^^^^^^^^^^^^ use of undeclared type or module `ElementState`
  
  error[E0433]: failed to resolve: use of undeclared type or module `MouseButton`
     --> src/main.rs:436:45
      |
  436 |                     (ElementState::Pressed, MouseButton::Right) => {
      |                                             ^^^^^^^^^^^ use of undeclared type or module `MouseBut
  
  error[E0433]: failed to resolve: use of undeclared type or module `WindowEvent`
     --> src/main.rs:444:13
      |
  444 |             WindowEvent::CursorMoved{device_id: _, position, modifiers: _} => {
      |             ^^^^^^^^^^^ use of undeclared type or module `WindowEvent`
  
  error[E0433]: failed to resolve: use of undeclared type or module `WindowEvent`
     --> src/main.rs:454:13
      |
  454 |             WindowEvent::MouseWheel{device_id: _, delta, phase: _, modifiers: _} => {
      |             ^^^^^^^^^^^ use of undeclared type or module `WindowEvent`
  
  error[E0433]: failed to resolve: use of undeclared type or module `MouseScrollDelta`
     --> src/main.rs:457:21
      |
  457 |                     MouseScrollDelta::LineDelta(x, y) => {
      |                     ^^^^^^^^^^^^^^^^ use of undeclared type or module `MouseScrollDelta`
  
  error[E0433]: failed to resolve: use of undeclared type or module `MouseScrollDelta`
     --> src/main.rs:460:21
      |
  460 |                     MouseScrollDelta::PixelDelta(position) => {
      |                     ^^^^^^^^^^^^^^^^ use of undeclared type or module `MouseScrollDelta`
  
  error[E0433]: failed to resolve: use of undeclared type or module `WindowEvent`
     --> src/main.rs:466:13
      |
  466 |             WindowEvent::KeyboardInput{device_id: _, input} => {
      |             ^^^^^^^^^^^ use of undeclared type or module `WindowEvent`
  
  error[E0433]: failed to resolve: use of undeclared type or module `ElementState`
     --> src/main.rs:468:22
      |
  468 |                     (ElementState::Released, Some(VirtualKeyCode::Escape)) => {
      |                      ^^^^^^^^^^^^ use of undeclared type or module `ElementState`
  
  error[E0433]: failed to resolve: use of undeclared type or module `VirtualKeyCode`
     --> src/main.rs:468:51
      |
  468 |                     (ElementState::Released, Some(VirtualKeyCode::Escape)) => {
      |                                                   ^^^^^^^^^^^^^^ use of undeclared type or module
  
  error[E0433]: failed to resolve: use of undeclared type or module `ElementState`
     --> src/main.rs:481:22
      |
  481 |                     (ElementState::Pressed, Some(VirtualKeyCode::Grave)) => {
      |                      ^^^^^^^^^^^^ use of undeclared type or module `ElementState`
  
  error[E0433]: failed to resolve: use of undeclared type or module `VirtualKeyCode`
     --> src/main.rs:481:50
      |
  481 |                     (ElementState::Pressed, Some(VirtualKeyCode::Grave)) => {
      |                                                  ^^^^^^^^^^^^^^ use of undeclared type or module `
  
  error[E0433]: failed to resolve: use of undeclared type or module `ElementState`
     --> src/main.rs:484:22
      |
  484 |                     (ElementState::Pressed, Some(VirtualKeyCode::F11)) => {
      |                      ^^^^^^^^^^^^ use of undeclared type or module `ElementState`
  
  error[E0433]: failed to resolve: use of undeclared type or module `VirtualKeyCode`
     --> src/main.rs:484:50
      |
  484 |                     (ElementState::Pressed, Some(VirtualKeyCode::F11)) => {
      |                                                  ^^^^^^^^^^^^^^ use of undeclared type or module `
  
  error[E0433]: failed to resolve: use of undeclared type or module `ElementState`
     --> src/main.rs:493:22
      |
  493 |                     (ElementState::Pressed, Some(key)) => {
      |                      ^^^^^^^^^^^^ use of undeclared type or module `ElementState`
  
  error[E0433]: failed to resolve: use of undeclared type or module `ElementState`
     --> src/main.rs:503:22
      |
  503 |                     (ElementState::Released, Some(key)) => {
      |                      ^^^^^^^^^^^^ use of undeclared type or module `ElementState`
  
  error[E0412]: cannot find type `WindowedContext` in module `glutin`
    --> src/gl/mod.rs:24:28
     |
  24 | pub fn init(vid: & glutin::WindowedContext<glutin::PossiblyCurrent>) {
     |                            ^^^^^^^^^^^^^^^ not found in `glutin`
  
  error[E0412]: cannot find type `PossiblyCurrent` in module `glutin`
    --> src/gl/mod.rs:24:52
     |
  24 | pub fn init(vid: & glutin::WindowedContext<glutin::PossiblyCurrent>) {
     |                                                    ^^^^^^^^^^^^^^^ not found in `glutin`
  
  error[E0412]: cannot find type `WindowedContext` in module `glutin`
     --> src/main.rs:357:45
      |
  357 | fn handle_window_event(window: &mut glutin::WindowedContext<glutin::PossiblyCurrent>,
      |                                             ^^^^^^^^^^^^^^^ not found in `glutin`
  
  error[E0412]: cannot find type `PossiblyCurrent` in module `glutin`
     --> src/main.rs:357:69
      |
  357 | fn handle_window_event(window: &mut glutin::WindowedContext<glutin::PossiblyCurrent>,
      |                                                                     ^^^^^^^^^^^^^^^ not found in `
  
  error[E0412]: cannot find type `Event` in module `glutin`
     --> src/main.rs:360:39
      |
  360 |                        event: glutin::Event) {
      |                                       ^^^^^ not found in `glutin`
  
  warning: unused import: `Digest`
    --> src/protocol/mojang.rs:15:18
     |
  15 | use sha1::{self, Digest};
     |                  ^^^^^^
     |
     = note: #[warn(unused_imports)] on by default
  
  warning: unused import: `serde_json::json`
    --> src/protocol/mojang.rs:16:5
     |
  16 | use serde_json::json;
     |     ^^^^^^^^^^^^^^^^
  
  warning: unused import: `std::thread`
    --> src/resources.rs:17:5
     |
  17 | use std::thread;
     |     ^^^^^^^^^^^
  
  warning: unused import: `zip`
    --> src/resources.rs:29:5
     |
  29 | use zip;
     |     ^^^
  
  warning: unused import: `GenericImage`
    --> src/render/mod.rs:29:13
     |
  29 | use image::{GenericImage, GenericImageView};
     |             ^^^^^^^^^^^^
  
  warning: unused import: `error`
    --> src/render/mod.rs:35:11
     |
  35 | use log::{error, trace};
     |           ^^^^^
  
  warning: unused import: `std::thread`
    --> src/screen/login.rs:18:5
     |
  18 | use std::thread;
     |     ^^^^^^^^^^^
  
  warning: unused import: `Rng`
    --> src/screen/login.rs:20:18
     |
  20 | use rand::{self, Rng};
     |                  ^^^
  
  warning: unused import: `crate::render`
    --> src/screen/login.rs:23:5
     |
  23 | use crate::render;
     |     ^^^^^^^^^^^^^
  
  warning: unused import: `crate::auth`
    --> src/screen/login.rs:27:5
     |
  27 | use crate::auth;
     |     ^^^^^^^^^^^
  
  warning: unused import: `glutin::*`
     --> src/main.rs:361:9
      |
  361 |     use glutin::*;
      |         ^^^^^^^^^
  
  warning: unused import: `std::io::Write`
    --> src/render/mod.rs:25:5
     |
  25 | use std::io::Write;
     |     ^^^^^^^^^^^^^^
  
  error: aborting due to 37 previous errors
  
  Some errors occurred: E0412, E0432, E0433.
  For more information about an error, try `rustc --explain E0412`.
  error: Could not compile `stevenarella`.
  
| To learn more, run the command again with --verbose.
Compiling your crate to WebAssembly
Caused by: Process exited with exit code: 101: `cargo build` did not exit successfully.

steven $ 
```
