### PR TITLE
wasm: Add println! logging to console.log

### PR DESCRIPTION
**Pull request by iceiix**
#92 added support for compiling to wasm32-unknown-unknown, but fails with #115. While investigating #115, found `println!` doesn't write to the JavaScript console log as would expect. Rectify this absence based on https://rustwasm.github.io/docs/book/game-of-life/debugging.html

### CODE REVIEW

**Comment by iceiix** [comment]
This works for the initial `println!`, but breaks on non-wasm:

thread 'main' panicked at 'function not implemented on non-wasm32 targets', .cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.45/src/lib.rs:487:1

attempted to move into `cfg_if!` but it makes it ambiguous:

```
error[E0659]: `println` is ambiguous (macro-expanded name vs less macro-expanded name from outer scope during import/macro resolution)
   --> src/main.rs:202:5
    |
202 |     println!("entering main");
    |     ^^^^^^^ ambiguous name
    |
    = note: `println` could refer to a macro from prelude
note: `println` could also refer to the macro defined here
   --> src/main.rs:189:9
    |
189 | /         macro_rules! println {
190 | |             ( $( $t:tt )* ) => {
191 | |                 web_sys::console::log_1(&format!( $( $t )* ).into());
192 | |             }
193 | |         }
    | |_________^
```

**Comment by iceiix** [comment]
Fixed the macro ambiguity, but `info!` isn't logged. A better approach may be to route `info!` etc. to console.log and replace the few uses of `println!` with `info!`.

**Comment by iceiix** [comment]
`console_log` works well, but Steven has its own logging setup:

```rust
    let con = Arc::new(Mutex::new(console::Console::new()));
    let proxy = console::ConsoleProxy::new(con.clone());

    log::set_boxed_logger(Box::new(proxy)).unwrap();
    log::set_max_level(log::LevelFilter::Trace);
```

This now fails setting the logger: stevenarella.js:45 panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', src/libcore/result.rs:997:5

**Comment by iceiix** [comment]
SetLoggerError is for when the logger is initialized twice, which is why splitting init_log to call either console_log::init_with_level or log::set_boxed_logger(Box::new(proxy)) fixed it.

But the ConsoleProxy is used for the in-game GUI console invoked by hitting the backtick key, so it *should* be logged to even for the web. ConsoleProxy's log fn just calls `println!`:

https://github.com/iceiix/stevenarella/blob/8071db668c2ee94f3e2a7eca50a968a702ce2825/src/console/mod.rs#L288-L292

This would be a better spot to send to the web console. Is it possible to forward one logger to another? [console_log](https://crates.io/crates/console_log) has the nice feature of sending warn! to console.warn, error! to console.error, etc., based on the log level, whereas our ConsoleProxy only does println!.

**Comment by iceiix** [comment]
Now I can see the expected logging output on wasm:

entering main
stevenarella.js:144 [main.rs:228][INFO] Starting steven

although had to disable config file loading to get to it.

36 total hits for println, shouldn't be too hard to replace with log crate macros.

**Comment by iceiix** [comment]
Screen Shot 2019-05-22 at 3 42 57 PM
